### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by tsrats** [MikeDombo/xen-exporter#6]
Hi! I am trying to run 2 instances of this exporter for my 2 xcp-ng hosts. They are both on the same version of code, but only 1 of the two works. The differences between the two servers are that one is AMD Ryzen (which works), the other is an Intel NUC (which doesn't), and the NUC has HDDs symlinked as passthrough drives to a VM.

When I run the exporter, the NUC instance shows the following over and over until it crashes:
```
10.244.5.1 - - [17/Jul/2023 18:45:05] "GET / HTTP/1.1" 200 -
10.244.5.1 - - [17/Jul/2023 18:45:07] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('10.244.5.1', 55276)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/app/xen-exporter.py", line 226, in __init__
    super().__init__(request, client_address, server)
  File "/usr/local/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/app/xen-exporter.py", line 232, in do_GET
    self.wfile.write(collect_metrics().encode("utf-8"))
  File "/usr/local/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
```

They are running in Kubernetes, but both are containers of the same VM on the same hypervisor (neither are running on xcp-ng, but ESXi). The containers host is on the same subnet as both servers, and both servers have the same username/password and SSL verify disabled.

I ran the HTTP call the code is doing (`https://<ip-of-host>/rrd_updates?start=1689620225&json=true&host=true&cf=AVERAGE`) using just a timestamp generated right before running it, and the output of the two looks mostly the same to me, nothing stands out as much different. I can provide that if needed. 

Any ideas of why this might be crashing as it is? Or what I can look at to get more information?

**Comment by MikeDombo** [comment]
The broken pipe is in the write method, which means we're trying to send the output metrics to the requestor, but the requestor already gave up. What is querying the xen metric exporter? Try configuring timeouts in that thing. This is not something which can be addressed in the code base here (except to catch the exception)

**Comment by MikeDombo** [comment]
I just made a change to the script to catch the error, so you can try that out. But do look into what I said before, have a look at your prometheus config for the metric collection timeout.

**Comment by tsrats** [comment]
I will update to the new script with the error catch, but the interesting thing is that this error occurs without Prometheus (or anything else) querying the collector.

**Comment by MikeDombo** [comment]
The exception is in the http response handler. It is impossible for any of this code to run without something querying the endpoint. But I'm not able to tell you what that thing would be.

**Comment by tsrats** [comment]
I guess in that case it would probably be the kubernetes health check. But what is odd is that both are configured the same, so they have the exact same health check as well.

**Comment by MikeDombo** [comment]
Looks like the default timeout for k8s is 1 second, so if scraping the metrics takes more than 1 second (which can happen, especially the first time), this exception may happen.

**Comment by tsrats** [comment]
Ah, ok that makes sense. Let me change the health check to every minute instead.

**Comment by MikeDombo** [comment]
The frequency doesn't matter much, what matters is the timeout, how long kubernetes will wait for a response.

**Comment by tsrats** [comment]
That was it! Changed to a 60 second check with a 30 second timeout, and it is running fine now. Thank you so much for the help!!

**Comment by tsrats** [comment]
Also wanted to note, I did make a helm chart for this project at https://github.com/tsrats/helm-charts. I need to add more documentation for the values.yaml file needed, but I wanted to share incase it might help anyone out.
