### ISSUE TITLE
I have only one host per datacenter, I can't see the rest in the exporter

### ISSUE THREAD

**Issue by Ngougniheguens** [MikeDombo/xen-exporter#8]
I connected the exporter to the pool master but I can only see one blade(host) per datacenter in the metrics exported.
``
![image](https://github.com/MikeDombo/xen-exporter/assets/66874059/91d7eeb5-ee79-454d-9d26-70b167b1fccc)

**Comment by MikeDombo** [comment]
Are these hosts all poolmasters or did you configure this script 4 times to hit each of them? I do not have multiple hosts to test with, but I _think_ the way things are currently written will have only 1 output per poolmaster within a cluster.

**Comment by Ngougniheguens** [comment]
Yes exactly I only have one host per poolmaster.

They are all poolmasters

I try a loop on the url variable, but I still have a host per poolmaster
`
with Xen("http://" + xen_poolmaster, xen_user, xen_password, verify_ssl) as xen:
            hosts_list = xen.xenapi.host.get_all()
            print(hosts_list)
            print()
            for host_list in hosts_list:
                print(host_list)
                xen_host_ip = xen.xenapi.host.get_address(host_list)
                url = f"http://{xen_host_ip}/rrd_updates?start={int(time.time()-10)}&json=true&host=true&cf=AVERAGE"
                req = urllib.request.Request(url)
`

**Comment by MikeDombo** [comment]
I believe this is what's expected, but I'm unable to test because I don't have an HA setup for xen.
If it is showing metrics for all the VMs on all hosts then that would be correct.
